#!/bin/bash

################################################################################
# Configure Mobile App for Physical Device
# This script helps set up the mobile app to work with your phone
################################################################################

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📱 Mobile App Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Get local IP
if [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "win32" ]]; then
    # Windows - Check for hotspot first, then WiFi
    echo -e "${BLUE}ℹ${NC} Detecting network adapter..."
    
    # Check for Mobile Hotspot (Local Area Connection* 10 or similar)
    HOTSPOT_IP=$(ipconfig | grep -A 5 "Local Area Connection\*" | grep "IPv4 Address" | head -1 | awk -F: '{print $2}' | tr -d ' ')
    
    if [ -n "$HOTSPOT_IP" ]; then
        echo -e "${GREEN}✓${NC} Found Mobile Hotspot IP"
        IP=$HOTSPOT_IP
    else
        # Get WiFi IP
        IP=$(ipconfig | awk '/Wireless LAN adapter WiFi:/{flag=1} flag && /IPv4 Address/{print $NF; exit}')
    fi
else
    # Mac/Linux - Get primary interface IP
    IP=$(ip route get 8.8.8.8 2>/dev/null | awk '{print $7; exit}')
    [ -z "$IP" ] && IP=$(hostname -I | awk '{print $1}')
fi

echo -e "${BLUE}ℹ${NC} Your computer's IP address: ${GREEN}$IP${NC}"
echo ""
echo "This IP will be used so your phone can connect to the backend."
echo ""

# Prompt user
read -p "Use this IP? (Y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    # Use detected IP
    API_URL="http://$IP:8000"
else
    # Manual entry
    read -p "Enter your IP address: " MANUAL_IP
    API_URL="http://$MANUAL_IP:8000"
fi

# Write to .env
cat > mobile/.env << EOF
# Mobile App Configuration
# Auto-generated by configure-mobile.sh

# Backend API URL - Updated $(date)
EXPO_PUBLIC_API_URL=$API_URL

# To use localhost (emulator/web browser), change to:
# EXPO_PUBLIC_API_URL=http://localhost:8000
EOF

echo ""
echo -e "${GREEN}✅${NC} Configuration saved!"
echo ""
echo "📝 mobile/.env has been updated with:"
echo "   EXPO_PUBLIC_API_URL=$API_URL"
echo ""
echo "📱 Next steps:"
echo "   1. Make sure your phone and computer are on the same WiFi"
echo "   2. Run: ./start.sh run"
echo "   3. Scan QR code with Expo Go app"
echo ""
echo "🔧 To test if backend is accessible from your phone:"
echo "   Open this URL in your phone's browser:"
echo "   $API_URL/docs"
echo ""
