@echo off
REM ============================================================================
REM Configure Mobile App for Physical Device (Windows)
REM ============================================================================

echo.
echo ================================================
echo   Mobile App Configuration
echo ================================================
echo.

echo [*] Detecting network adapter...
echo.

REM Check for Mobile Hotspot first
set IP=
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr "Local Area Connection\*" -A 5 ^| findstr "IPv4 Address"') do (
    set IP=%%a
    echo [*] Found Mobile Hotspot IP
    goto :found_ip
)

REM Get WiFi IP
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr "Wireless LAN adapter WiFi" -A 5 ^| findstr "IPv4 Address"') do (
    set IP=%%a
    goto :found_ip
)

:found_ip
REM Trim spaces
set IP=%IP: =%

if "%IP%"=="" (
    echo [ERROR] Could not detect WiFi IP address
    echo [*] Please check that WiFi is connected
    pause
    exit /b 1
)

echo [*] Your WiFi IP address: %IP%
echo.
echo This IP will be used so your phone can connect to the backend.
echo.

set /p USE_IP="Use this IP? (Y/n): "
if /i "%USE_IP%"=="n" (
    set /p IP="Enter your IP address: "
)

set API_URL=http://%IP%:8000

REM Write to .env
(
echo # Mobile App Configuration
echo # Auto-generated by configure-mobile.bat
echo.
echo # Backend API URL - Updated %date% %time%
echo EXPO_PUBLIC_API_URL=%API_URL%
echo.
echo # To use localhost ^(emulator/web browser^), change to:
echo # EXPO_PUBLIC_API_URL=http://localhost:8000
) > mobile\.env

echo.
echo [OK] Configuration saved!
echo.
echo [*] mobile\.env has been updated with:
echo     EXPO_PUBLIC_API_URL=%API_URL%
echo.
echo [*] Next steps:
echo     1. Make sure your phone and computer are on the same WiFi
echo     2. Run: start.bat run
echo     3. Scan QR code with Expo Go app
echo.
echo [*] To test if backend is accessible from your phone:
echo     Open this URL in your phone's browser:
echo     %API_URL%/docs
echo.
pause
